{% set name = "nvcc" %}
{% set number = 12 %}

{% if cuda_compiler_version in (undefined, None, "None") %}
{% set cuda_major = 0 %}
{% set cuda_minor = 0 %}
{% set cuda_major_minor = (0, 0) %}
{% else %}
{% set cuda_major = environ.get("cuda_compiler_version", "11.1").split(".")[0]|int %}
{% set cuda_minor = environ.get("cuda_compiler_version", "11.1").split(".")[1]|int %}
{% set cuda_major_minor = (cuda_major, cuda_minor) %}
{% endif %}

package:
  name: "{{ name }}"

build:
  number: {{ number }}
{% if cuda_major == 0 %}
  skip: true
{% endif %}

outputs:
  - name: "{{ name }}_{{ target_platform }}"
    version: "{{ cuda_compiler_version }}"
    number: {{ number }}
    script: install_nvcc.sh   # [linux]
    script: windows/install_nvcc.bat  # [win]
    build:
      ignore_run_exports:
        - libgcc-ng
      run_exports:
        strong:
          - cudatoolkit {{ cuda_compiler_version }}|{{ cuda_compiler_version }}.*
{% if cuda_major_minor >= (11, 0) %}
          - __glibc >=2.17
{% endif %}
    requirements:
      build:      # [win]
        - m2-sed  # [win]
      host:
        # Needed to symlink libcuda into sysroot libs.
        - {{ compiler("c") }}
{% if cuda_major_minor >= (11, 0) %}
        - sysroot_linux-64 2.17
        - __glibc >=2.17
{% endif %}
      run:
        - sed                     # [linux]
{% if cuda_major_minor >= (11, 0) %}
        - sysroot_linux-64 2.17
        - __glibc >=2.17
{% endif %}
    test:
      requires:
        - {{ compiler("c") }}
        # Host code is forwarded to a C++ compiler
        - {{ compiler("cxx") }}
{% if cuda_major_minor >= (11, 0) %}
        - sysroot_linux-64 2.17
{% endif %}
      files:
        - test.cu
        - test_nvcc.sh  # [linux]
        - windows\test_nvcc.bat  # [win]
      commands:
        - bash test_nvcc.sh  # [linux]
        - windows\test_nvcc.bat  # [win]
    about:
      home: https://github.com/conda-forge/nvcc-feedstock
      license: BSD-3-Clause
      license_file: LICENSE.txt
      summary: A meta-package to enable the right nvcc.

about:
  home: https://github.com/conda-forge/nvcc-feedstock
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: A meta-package to enable the right nvcc.

extra:
  recipe-maintainers:
    - dillon-cullinan
    - isuruf
    - jakirkham
    - kkraus14
    - mike-wendt
    - raydouglass
    - jaimergp
